config/routes.rb
Rails.application.routes.draw do
  
  resources :cash_in_outs
  resources :money_trans
  resources :fuel_trans
  resources :users

  root 'static_pages#home'
  get '/root', to: 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get  '/contact',    to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
	get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/dashboards_fueltran', to: 'dashboards#fueltran'
  get '/dashboards_moneytran',to: 'dashboards#moneytran'
  get '/dashboards_cashinout',to: 'dashboards#cashinout'
  get '/maindashboards', to: 'dashboards#maindashboard'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

 

app/models/fuel_tran.rb
class FuelTran < ApplicationRecord

	validates :date, presence: true
	validates :qty, presence: true
	validates :price, presence: true

	def self.multiply(qty,price)
		return qty * price
	end

	
end

app/controllers/fuel_trans_controller.rb
class FuelTransController < ApplicationController

  before_action :set_fuel_tran, only: [:show, :edit, :update, :destroy]
  before_action :total_gp, only: [:index, :show]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,:show]

  # GET /fuel_trans
  # GET /fuel_trans.json
  def index
    @fuel_trans = FuelTran.all
    @total_gross_profi 
  end

  # GET /fuel_trans/1
  # GET /fuel_trans/1.json
  def show
    @total_gross_profit
  end

  # GET /fuel_trans/new
  def new
    @fuel_tran = FuelTran.new 
  end

  # GET /fuel_trans/1/edit
  def edit
  end

  # POST /fuel_trans
  # POST /fuel_trans.json
  def create
    @fuel_tran = FuelTran.new(fuel_tran_params)
    @isChecked = params[:fuel_tran][:trans_type]
    if  @isChecked == 'true'
      @fuel_tran.trans_type = '01'
    else
      @fuel_tran.trans_type = '02'
    end
    @fuel_tran.created_by = current_user[:id]
    @fuel_tran.updated_by = current_user[:id]
    respond_to do |format|
      if @fuel_tran.save
        @fuel_trans = FuelTran.all
        @amount = FuelTran.multiply(@fuel_tran.qty,@fuel_tran.price)
        @fuel_trans.each do |fuel_tran|
          @buy_qty = FuelTran.where(:trans_type => fuel_tran.trans_type ='01').sum(:qty)
          @sale_qty = FuelTran.where(:trans_type => fuel_tran.trans_type ='02').sum(:qty)
          @stock_balance = @buy_qty - @sale_qty
          @fuel_tran.update_attributes(:stock_balance => @stock_balance,:amount => @amount)
        end
        format.html { redirect_to @fuel_tran, notice: 'Fuel transaction was successfully created.'}
        format.json { render :show,:index, status: :created, location: @fuel_tran }
      else
        format.html { render :new }
        format.json { render json: @fuel_tran.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fuel_trans/1
  # PATCH/PUT /fuel_trans/1.json
  def update 
      respond_to do |format|
      if @fuel_tran.update(fuel_tran_params)
        format.html { redirect_to @fuel_tran}
        format.json { render :show, status: :ok, location: @fuel_tran }
      else
        format.html { render :edit }
        format.json { render json: @fuel_tran.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fuel_trans/1
  # DELETE /fuel_trans/1.json
  def destroy
    @fuel_tran.destroy
    respond_to do |format|
      format.html { redirect_to fuel_trans_url, notice: 'Fuel tran was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fuel_tran
      @fuel_tran = FuelTran.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fuel_tran_params
      params.require(:fuel_tran).permit(:date, :qty, :price)
    end

    def total_gp
      @fuel_trans = FuelTran.all
        @fuel_trans.each do |fuel_tran|
        @buy_qty = FuelTran.where(:trans_type => fuel_tran.trans_type ='01').sum(:qty)
        @buy_amount = FuelTran.where(:trans_type => fuel_tran.trans_type ='01').sum(:amount)
        @buy_unitprice = @buy_amount / @buy_qty

        @sale_qty = FuelTran.where(:trans_type => fuel_tran.trans_type ='02').sum(:qty)
        @sale_amount = FuelTran.where(:trans_type => fuel_tran.trans_type ='02').sum(:amount)
        @sale_unitprice = @sale_amount / @sale_qty

        @total_gross_profit = (@sale_unitprice * @sale_qty) - (@buy_unitprice * @buy_qty)
      end
    end
end

app/helpers/fuel_trans_helper.rb
module FuelTransHelper
end

app/views/fuel_trans/_form.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: fuel_tran, local: true) do |form| %>
      <% if fuel_tran.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(fuel_tran.errors.count, "error") %> prohibited this fuel_tran from being saved:</h2>

          <ul>
          <% fuel_tran.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
  
      <div class="field">
        <%= form.label :date %>
        <%= form.text_field :date, :id => 'datepicker', :value => fuel_tran.date.strftime("%d-%b-%Y"), class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :qty,:value=> "Quantity" %>
        <%= form.number_field :qty, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :price %>
        <%= form.text_field :price, class: 'form-control' %>
      </div>

      <%= form.label :buy, class: "radio-button inline" do%>
        <%= form.radio_button :trans_type ,true,:checked => (fuel_tran.trans_type == 01) %>
        <span>Buy Transaction</span>
      <% end %>

      <%= form.label :sale, class: "radio-button inline" do%>
        <%= form.radio_button :trans_type , false, :checked => (fuel_tran.trans_type == 02)%>
        <span>Sale Transaction</span>
      <% end %>

      <div class="actions">
        <%= form.submit :class => "btn btn-info" %>
      </div>
      <%= link_to 'Show', @fuel_tran %> | <%= link_to 'Back', fuel_trans_path %>
    <% end %>
  </div>
</div>


<script>
  $('#datepicker').datepicker({format: 'dd-M-yyyy'});
</script>

app/views/fuel_trans/_newform.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: fuel_tran, local: true) do |form| %>
      <% if fuel_tran.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(fuel_tran.errors.count, "error") %> prohibited this fuel_tran from being saved:</h2>

          <ul>
          <% fuel_tran.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
  
      <div class="field">
        <%= form.label :date %>
        <%= form.text_field :date, :id => 'datepicker', :value => Date.today().strftime("%d-%b-%Y"), class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :qty ,:value=> "Quantity"%>
        <%= form.number_field :qty, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :price %>
        <%= form.number_field :price, class: 'form-control'%>
      </div>

      <%= form.label :buy, class: "radio_button inline" do %>
        <%= form.radio_button :trans_type ,true%>
        <span>Buy Transaction</span>
      <% end %>

      <%= form.label :sale, class: "radio_button inline" do %>
        <%= form.radio_button :trans_type , false%>
        <span>Sale Transaction</span>
      <% end %>

      <div class="actions">
        <%= form.submit :class => "btn btn-info" %>
      </div>
      <%= link_to 'Back', fuel_trans_path %>
    <% end %>
  </div>
</div>

<script>
  $('#datepicker').datepicker({format: 'dd-M-yyyy'});
</script>

app/views/fuel_trans/edit.html.erb
<h1>Editing Fuel Transaction</h1>

<%= render 'form', fuel_tran: @fuel_tran %>

app/views/fuel_trans/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-info">
        <div class="panel-heading">
          Fuel Transactions
        </div>
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Date</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Amount</th>
                <th>Stock Balance</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @fuel_trans.each do |fuel_tran| %>
                <tr>
                  <td><%= fuel_tran.date.strftime("%d-%b-%Y") %></td>
                  <td><%= fuel_tran.qty %></td>
                  <td><%= number_to_currency(fuel_tran.price) %></td>
                  <td><%= number_to_currency(fuel_tran.amount)%></td>
                  <td><%= fuel_tran.stock_balance %></td>
                  <td><%= link_to 'Show', fuel_tran %></td>
                  <td><%= link_to 'Edit', edit_fuel_tran_path(fuel_tran) %></td>
                  <td><%= link_to 'Destroy', fuel_tran, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>   
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel-info">
        <div class="panel-heading">
          Total Gross Profit
        </div>
        <div class="panel-body">
          <h3>
            <%= number_to_currency(@total_gross_profit) %>
          </h3>
          <div>
            <canvas id="mycanvas" class="line-chart"></canvas>
          </div>          
        </div>
      </div>
    </div>
  </div>
  <%= link_to "Add New Fuel Transaction", new_fuel_tran_path%>
</div>

<script src="sparkline.js"></script>
<script>
  sparkline ('mycanvas', [98,78,124,35,89,25,24,23,9,23,78,121,123,130], true);
</script>

app/views/fuel_trans/new.html.erb
<h1>New Fuel Transaction</h1>

<%= render 'newform', fuel_tran: @fuel_tran %>

app/views/fuel_trans/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @fuel_tran.date.strftime("%d-%b-%Y") %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @fuel_tran.qty %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@fuel_tran.price) %>
</p>

<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@fuel_tran.amount) %>
</p>

<p>
  <strong>Stock Balance:</strong>
  <%= @fuel_tran.stock_balance %>
</p>

<p>
  <strong>Total Gross Profit:</strong>
  <%= number_to_currency(@total_gross_profit) %>
</p>


<%= link_to 'Edit', edit_fuel_tran_path(@fuel_tran) %> |
<%= link_to 'Back', fuel_trans_path %>


  