config/routes.rb
Rails.application.routes.draw do
  
  resources :cash_in_outs
  resources :money_trans
  resources :fuel_trans
  resources :users

  root 'static_pages#home'
  get '/root', to: 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get  '/contact',    to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
	get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/dashboards_fueltran', to: 'dashboards#fueltran'
  get '/dashboards_moneytran',to: 'dashboards#moneytran'
  get '/dashboards_cashinout',to: 'dashboards#cashinout'
  get '/maindashboards', to: 'dashboards#maindashboard'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

 

app/models/money_tran.rb
class MoneyTran < ApplicationRecord

	validates :date, presence: true
	validates :qty, presence: true
	validates :price, presence: true

	def self.multiply(qty,price)
		return qty * price
	end

end

app/controllers/money_trans_controller.rb
class MoneyTransController < ApplicationController
  before_action :set_money_tran, only: [:show, :edit, :update, :destroy]
  before_action :total_gp, only: [:index, :show]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]

  # GET /money_trans
  # GET /money_trans.json
  def index
    @money_trans = MoneyTran.all
    @total_gross_profit 
  end

  # GET /money_trans/1
  # GET /money_trans/1.json
  def show
    @total_gross_profit
  end

  # GET /money_trans/new
  def new
    @money_tran = MoneyTran.new
  end

  # GET /money_trans/1/edit
  def edit
  end

  # POST /money_trans
  # POST /money_trans.json
  def create
    @money_tran = MoneyTran.new(money_tran_params)
    @isChecked = params[:money_tran][:trans_type]
    if  @isChecked == 'true'
      @money_tran.trans_type = '01'
    else
      @money_tran.trans_type = '02'
    end
    @money_tran.created_by = current_user[:id]
    @money_tran.updated_by = current_user[:id]
    respond_to do |format|
      if @money_tran.save
        @money_trans = MoneyTran.all
        @amount = MoneyTran.multiply(@money_tran.qty,@money_tran.price)
        @money_trans.each do |money_tran|
          @buy_qty = MoneyTran.where(:trans_type => money_tran.trans_type ='01').sum(:qty)
          @sale_qty = MoneyTran.where(:trans_type => money_tran.trans_type ='02').sum(:qty)
          @money_balance = @buy_qty - @sale_qty
          @money_tran.update_attributes(:money_balance => @money_balance,:amount => @amount)
        end
        format.html { redirect_to @money_tran, notice: 'Money tran was successfully created.' }
        format.json { render :show, status: :created, location: @money_tran }
      else
        format.html { render :new }
        format.json { render json: @money_tran.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /money_trans/1
  # PATCH/PUT /money_trans/1.json
  def update
    respond_to do |format|
      if @money_tran.update(money_tran_params)
        format.html { redirect_to @money_tran, notice: 'Money tran was successfully updated.' }
        format.json { render :show, status: :ok, location: @money_tran }
      else
        format.html { render :edit }
        format.json { render json: @money_tran.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /money_trans/1
  # DELETE /money_trans/1.json
  def destroy
    @money_tran.destroy
    respond_to do |format|
      format.html { redirect_to money_trans_url, notice: 'Money tran was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_money_tran
      @money_tran = MoneyTran.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def money_tran_params
      params.require(:money_tran).permit(:date, :qty, :price, :amount)
    end

    def total_gp
      @money_trans = MoneyTran.all
        @money_trans.each do |money_tran|
        @buy_qty = MoneyTran.where(:trans_type => money_tran.trans_type ='01').sum(:qty)
        @buy_amount = MoneyTran.where(:trans_type => money_tran.trans_type ='01').sum(:amount)
        @buy_unitprice = (@buy_amount / @buy_qty).round(4)

        @sale_qty = MoneyTran.where(:trans_type => money_tran.trans_type ='02').sum(:qty)
        @sale_amount = MoneyTran.where(:trans_type => money_tran.trans_type ='02').sum(:amount)
        @sale_unitprice = (@sale_amount / @sale_qty).round(4)

        @total_gross_profit = (@sale_unitprice * @sale_qty) - (@buy_unitprice * @buy_qty)
      end
    end
end

app/helpers/money_trans_helper.rb
module MoneyTransHelper
end

app/views/money_trans/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: money_tran, local: true) do |form| %>
      <% if money_tran.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(money_tran.errors.count, "error") %> prohibited this money_tran from being saved:</h2>

          <ul>
          <% money_tran.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
  
      <div class="field">
        <%= form.label :date %>
        <%= form.text_field :date, :id => 'datepicker', :value => money_tran.date.strftime("%d-%b-%Y") , class: 'form-control'%>
      </div>

      <div class="field">
        <%= form.label :qty,:value=> "Quantity" %>
        <%= form.number_field :qty, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :price %>
        <%= form.text_field :price, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :amount %>
        <%= form.text_field :amount, class: 'form-control' %>
      </div>

      <%= form.label :buy, class: "radio_button inline" do %>
        <%= form.radio_button :trans_type ,true%>
        <span>Buy Transaction</span>
      <% end %>

      <%= form.label :sale, class: "radio_button inline" do %>
        <%= form.radio_button :trans_type , false%>
        <span>Sale Transaction</span>
      <% end %>

      <div class="actions">
        <%= form.submit :class => "btn btn-info" %>
      </div>
      <%= link_to 'Show', @money_tran %> | <%= link_to 'Back', money_trans_path %>
    <% end %>
  </div>
</div>


<script>
  $('#datepicker').datepicker({format: 'dd-M-yyyy'});
</script>

app/views/money_trans/_newform.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: money_tran, local: true) do |form| %>
      <% if money_tran.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(money_tran.errors.count, "error") %> prohibited this money_tran from being saved:</h2>

          <ul>
          <% money_tran.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :date %>
       <%= form.text_field :date, :id => 'datepicker', :value => Date.today().strftime("%d-%b-%Y") , class: 'form-control'%>
      </div>

      <div class="field">
        <%= form.label :qty , :value=> "Quantity"%>
        <%= form.number_field :qty, class: 'form-control' %>
      </div>

      <div class="field">
        <%= form.label :price %>
        <%= form.text_field :price, class: 'form-control' %>
      </div>

      <%= form.label :buy, class: "radio_button inline" do %>
        <%= form.radio_button :trans_type ,true%>
        <span>Buy Transaction</span>
      <% end %>

      <%= form.label :sale, class: "radio_button inline" do %>
        <%= form.radio_button :trans_type , false%>
        <span>Sale Transaction</span>
      <% end %>

      <div class="actions">
        <%= form.submit :class => "btn btn-info"%>
      </div>
      <%= link_to 'Back', money_trans_path %>
    <% end %>
  </div>
</div>

<script>
  $('#datepicker').datepicker({format: 'dd-M-yyyy'});
</script>

app/views/money_trans/edit.html.erb
<h1>Editing Money Transaction</h1>

<%= render 'form', money_tran: @money_tran %>

app/views/money_trans/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="panel panel-info">
        <div class="panel-heading">
          Money Transactions
        </div>
        <div class="panel-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>Date</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Amount</th>
                <th>Stock Balance</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @money_trans.each do |money_tran| %>
                <tr>
                  <td><%= money_tran.date.strftime("%d-%b-%Y") %></td>
                  <td><%= money_tran.qty %></td>
                  <td><%= number_to_currency(money_tran.price) %></td>
                  <td><%= number_to_currency(money_tran.amount) %></td>
                  <td><%= number_to_currency(money_tran.money_balance) %></td>
                  <td><%= link_to 'Show', money_tran %></td>
                  <td><%= link_to 'Edit', edit_money_tran_path(money_tran) %></td>
                  <td><%= link_to 'Destroy', money_tran, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>   
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel-info">
        <div class="panel-heading">
          Total Gross Profit
        </div>
        <div class="panel-body">
          <h3>
            <%= number_to_currency(@total_gross_profit) %>
          </h3>
          <div>
            <canvas id="mycanvas" class="line-chart"></canvas>
          </div>          
        </div>
      </div>
    </div>
  </div>
  <%= link_to "Add New Money Transaction", new_money_tran_path%>
</div>

<script src="sparkline.js"></script>
<script>
sparkline ('mycanvas', [98,78,124,35,89,25,24,23,9,23,78,121,123,130], true)
;
</script>

app/views/money_trans/new.html.erb
<h1>New Money Transaction</h1>

<%= render 'newform', money_tran: @money_tran %>

app/views/money_trans/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @money_tran.date.strftime("%d-%b-%Y") %>
</p>

<p>
  <strong>Qty:</strong>
  <%= @money_tran.qty %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@money_tran.price) %>
</p>

<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@money_tran.amount) %>
</p>

<p>
  <strong>Money Balance:</strong>
  <%= number_to_currency(@money_tran.money_balance) %>
</p>

<%= link_to 'Edit', edit_money_tran_path(@money_tran) %> |
<%= link_to 'Back', money_trans_path %>