config/routes.rb
Rails.application.routes.draw do
  
  resources :cash_in_outs
  resources :money_trans
  resources :fuel_trans
  resources :users

  root 'static_pages#home'
  get '/root', to: 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get  '/contact',    to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
	get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/dashboards_fueltran', to: 'dashboards#fueltran'
  get '/dashboards_moneytran',to: 'dashboards#moneytran'
  get '/dashboards_cashinout',to: 'dashboards#cashinout'
  get '/maindashboards', to: 'dashboards#maindashboard'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

 

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy by May Myat Mon</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><a href="http://news.railstutorial.org/">News</a></li>
        <li><%= link_to "Help",   help_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default bg-white">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar" id="span-design"></span>
        <span class="icon-bar" id="span-design"></span>
        <span class="icon-bar" id="span-design"></span> 
      </button>
      <a class="navbar-brand fa fa-tachometer" href="/" id="logo"></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <% if current_user.role_id == 1 %>
            <li><%= link_to "Main Dashboard", maindashboards_path%></li>
          <%elsif current_user.role_id == 2%>
            <li><%= link_to "Main Dashboard", maindashboards_path%></li>
            <li><%= link_to "Fuel Transactions",  fuel_trans_path%></li>
          <% else %>
            <li><%= link_to "Main Dashboard", maindashboards_path%></li>
            <li><%= link_to "Currency Transactions",  money_trans_path%></li>
            <li><%= link_to "Cash In-Out",  cash_in_outs_path%></li>
          <% end %>  
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div> 
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FuelManagementSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>" id="alert"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
  <div class="container">
    <%= render 'layouts/footer' %>
  </div>
</html>